
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FoodDBService", targetNamespace = "http://soap.workshop.java.simplon.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FoodDBService {


    /**
     * 
     * @param carb
     * @param prot
     * @param name
     * @param fat
     * @param categoryName
     * @param energy
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "FoodAttributeId", targetNamespace = "")
    @RequestWrapper(localName = "createFoodAttribute", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.CreateFoodAttribute")
    @ResponseWrapper(localName = "createFoodAttributeResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.CreateFoodAttributeResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/createFoodAttributeRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/createFoodAttributeResponse")
    public int createFoodAttribute(
        @WebParam(name = "categoryName", targetNamespace = "")
        String categoryName,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "energy", targetNamespace = "")
        int energy,
        @WebParam(name = "prot", targetNamespace = "")
        int prot,
        @WebParam(name = "fat", targetNamespace = "")
        int fat,
        @WebParam(name = "carb", targetNamespace = "")
        int carb);

    /**
     * 
     * @param foodAttributeId
     * @return
     *     returns client.FoodAttribute
     */
    @WebMethod
    @WebResult(name = "FoodAttribute", targetNamespace = "")
    @RequestWrapper(localName = "getFoodAttributeById", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.GetFoodAttributeById")
    @ResponseWrapper(localName = "getFoodAttributeByIdResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.GetFoodAttributeByIdResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeByIdRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeByIdResponse")
    public FoodAttribute getFoodAttributeById(
        @WebParam(name = "foodAttributeId", targetNamespace = "")
        int foodAttributeId);

    /**
     * 
     * @param nameFilter
     * @return
     *     returns java.util.List<client.FoodAttribute>
     */
    @WebMethod
    @WebResult(name = "FoodAttribute", targetNamespace = "")
    @RequestWrapper(localName = "getFoodAttributeListByName", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.GetFoodAttributeListByName")
    @ResponseWrapper(localName = "getFoodAttributeListByNameResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.GetFoodAttributeListByNameResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeListByNameRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeListByNameResponse")
    public List<FoodAttribute> getFoodAttributeListByName(
        @WebParam(name = "nameFilter", targetNamespace = "")
        String nameFilter);

    /**
     * 
     * @return
     *     returns java.util.List<client.FoodCategory>
     */
    @WebMethod
    @WebResult(name = "FoodCategory", targetNamespace = "")
    @RequestWrapper(localName = "getFoodCategories", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.GetFoodCategories")
    @ResponseWrapper(localName = "getFoodCategoriesResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.GetFoodCategoriesResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodCategoriesRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodCategoriesResponse")
    public List<FoodCategory> getFoodCategories();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "PingResult1", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.PingResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/pingRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/pingResponse")
    public int ping();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "PingResult2", targetNamespace = "")
    @RequestWrapper(localName = "ping2", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.Ping2")
    @ResponseWrapper(localName = "ping2Response", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "client.Ping2Response")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/ping2Request", output = "http://soap.workshop.java.simplon.co/FoodDBService/ping2Response")
    public int ping2();

}
