package client;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server/HelloWorld/getHelloWorldAsStringRequest", output = "http://server/HelloWorld/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns wsimport.Personne
     */
    @WebMethod
    @WebResult(partName = "Personne")
    @Action(input = "http://server/HelloWorld/getPersonneRequest", output = "http://server/HelloWorld/getPersonneResponse")
    public Personne getPersonne(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);
    
    /**
     * 
     * @return
     *     returns wsimport.Personnes
     */
    @WebMethod
    @WebResult(name = "Personnes", partName = "Personnes")
    @Action(input = "http://server/HelloWorld/getPersonnesRequest", output = "http://server/HelloWorld/getPersonnesResponse")
    public Personnes getPersonnes();

}